export const SEARCH_CONTACT = "SEARCH_CONTACT";
export const SET_CONTACTS = "SET_CONTACTS";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const SET_FAVORITES = "SET_FAVORITES";
export const SHOW_FAVORITES = "SHOW_FAVORITES";
export const SORT_ASCENDING = "SORT_ASCENDING";
export const SORT_DESCENDING = "SORT_DESCENDING";
